#!/usr/bin/env zsh

zparseopts -D -F -- s=skip -skip=skip || return 1

local file
for file in "${@}"; do
  if [[ ! -r "${file}" ]]; then
    if ! (( ${#skip} )); then
      >&2 echo "[$0] No Readable File: ${file}"
    fi

    continue
  fi

  :zcompile "${file}" || continue

  builtin source -- "${file}"
done
